### ISSUE TITLE
Solution for subcollection rule files

### ISSUE THREAD

**Issue by mikemclin** [lupas/firestore-rulez#1]
Currently, this package concatenates "top-level" collection rules.  If I want to include rules for subcollections, then I must embed them in it's parent collection.  It would be nice to have the ability to separate those files as well.

This could be done automatically, perhaps, based the directory structure of the rules.

**Comment by lupas** [comment]
Hi @mikemclin 

Thanks for the input and sorry for the late reply, travelling keeps me busy. 

Do I understand correctly?

You would like to split the individual .rules files further into smaller sub-files for each sub-collection, right?

I guess we could do something likes this:

/rules
/rules/rule1.rule      --> works already 
/rules/rule2/rule2a.rule    --> what you want
/rules/rule2/rule2b.rule    --> what you want

In case there is a folder in the /rules directory, it concatenates the files in contains into a single rule and then again concentrates this into the final file. That would work. And we could make this work recursively working on an unlimited amount of subfolders.

Is that what you're talking about?

If so, feel free to make a pull request. I'm travelling and can't promise to have enough time to look at it in the next few weeks or months.

**Comment by lupas** [comment]
Closed due to inactivity.
