### ISSUE TITLE
No support for rules version 2

### ISSUE THREAD

**Issue by azzamasghar1** [lupas/firestore-rulez#2]
Currently this package does not support rules_version: '2' as specified here:
https://firebase.google.com/docs/firestore/security/get-started#security_rules_version_2

I guess we can create two templates for header in `templates` folder one which has same old 
`service cloud.firestore {`
	`match /databases/{database}/documents {`

and a second which can have 
`rules_version = '2';`
`service cloud.firestore {`
	`match /databases/{database}/documents {`
to support rules version 2.

Furthermore a new configuration variable can be added let's say `rules_version` which can be used to decide which header template should be used.

This is a great little tool and it would really be good to have this support built in i guess.

**Comment by lupas** [comment]
Added with [v0.2.0](https://github.com/lupas/firestore-rulez/releases/tag/v0.2.0), thanks a lot @azzamasghar1 !
